# Generated by Django 3.2.9 on 2021-11-27 21:06

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('sc_name', models.CharField(max_length=1000, unique=True, verbose_name='Science Club Name')),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('profile_image', models.ImageField(blank=True, upload_to='uploads/club/profile_image')),
                ('background_image', models.ImageField(blank=True, upload_to='uploads/club/background_image')),
                ('about', models.CharField(blank=True, max_length=5000)),
            ],
            options={
                'verbose_name': 'Science Club',
                'verbose_name_plural': 'Science Clubs',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, unique=True, verbose_name='Project title')),
                ('about', models.CharField(max_length=5000)),
                ('image', models.ImageField(blank=True, upload_to='uploads/club/project_image')),
                ('active', models.BooleanField()),
                ('start_date', models.DateField()),
                ('deadline', models.DateField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.club', verbose_name='Science Club')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Post title')),
                ('image', models.ImageField(blank=True, upload_to='uploads/club/post_image')),
                ('contents', models.CharField(max_length=5000)),
                ('publication_date', models.DateTimeField(default=datetime.datetime(2021, 11, 27, 22, 6, 2, 552998))),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.club', verbose_name='Science Club')),
            ],
        ),
    ]
