# Generated by Django 3.2.9 on 2021-11-29 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='about',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='club',
            name='background_image',
            field=models.ImageField(blank=True, default='uploads/club/background_image/default_background.png', upload_to='uploads/club/background_image'),
        ),
        migrations.AlterField(
            model_name='club',
            name='profile_image',
            field=models.ImageField(blank=True, default='uploads/club/profile_image/default_profile.jpg', upload_to='uploads/club/profile_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 0, 26, 1, 851304)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Project title'),
        ),
    ]
