# Generated by Django 3.2.9 on 2021-11-29 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_auto_20211130_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 0, 33, 24, 606673)),
        ),
    ]
